monolog:
    handlers:
        main:
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: INFO
            channels: ["!event", "!doctrine"]
            formatter: Monolog\Formatter\JsonFormatter
            max_files: 3
            type: rotating_file
        nested:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
